name: Check and Test Package
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-test:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install Roc
        uses: hasnep/setup-roc@v0.5.0
        with:
          roc-version: alpha3-rolling
      - name: Roc check on all roc files in src
        run: for roc_file in ./src/*.roc; do roc check $roc_file; done
      - name: Roc test on src/main.roc
        run: roc test src/main.roc
      - name: Roc build on src/main.roc
        run: roc build src/main.roc